/**
 * 
 * You've been given a code snippet that creates random HexCodes for colors, however there seems to be a bug with the code that sometimes return 5 hex digits instead of 6.

Can you find out the bug and fix it. You can modify the function code to always return a proper hexCode. You have been also given a sample snippet to see the hex Codes generated by the function.

Here is how a sample hex Code looks like


 * Returns a 6 digit hexCode prepended with '#' as a valid color code
 * @returns {string} hexCode
 */
 function generateRandomHexCode() {
	let hexCode = "#";

	for (let i = 0; i <3; i++) {
		hexCode += Math.floor(Math.random() * 256).toString(16).padStart(2,'0');
       
	}

	return hexCode;
}

// You can log the results of the function to debug
// Sample Strings
function test (){
for (let i = 0; i < 100; i++) {
	console.log(generateRandomHexCode());
}
}
test();